CATEGORIES = [
    "Processor",
    "Motherboard",
    "RAM",
    "ROM / Storage",
    "Graphics Card",
    "Wi-Fi Card",
    "Power Supply",
    "Cabinet",
]


PRODUCTS = [
    {
        "category": "Processor",
        "name": "AMD Ryzen 5 5600",
        "brand": "AMD",
        "price": 12100,
        "office": 82,
        "gaming": 76,
        "home": 80,
        "creator": 72,
        "socket": "AM4",
        "wattage": 65,
        "capability": 72,
        "details": "6 cores, 12 threads, DDR4 value build",
    },
    {
        "category": "Processor",
        "name": "AMD Ryzen 5 7600",
        "brand": "AMD",
        "price": 18900,
        "office": 88,
        "gaming": 88,
        "home": 86,
        "creator": 82,
        "socket": "AM5",
        "wattage": 65,
        "capability": 84,
        "details": "6 cores, 12 threads, DDR5 platform",
    },
    {
        "category": "Processor",
        "name": "AMD Ryzen 7 7700",
        "brand": "AMD",
        "price": 28600,
        "office": 92,
        "gaming": 91,
        "home": 88,
        "creator": 90,
        "socket": "AM5",
        "wattage": 65,
        "capability": 90,
        "details": "8 cores, efficient gaming and editing CPU",
    },
    {
        "category": "Processor",
        "name": "AMD Ryzen 7 7800X3D",
        "brand": "AMD",
        "price": 36500,
        "office": 90,
        "gaming": 98,
        "home": 88,
        "creator": 86,
        "socket": "AM5",
        "wattage": 120,
        "capability": 95,
        "details": "Excellent gaming CPU with 3D V-Cache",
    },
    {
        "category": "Processor",
        "name": "Snapdragon X Elite Mini PC Platform",
        "brand": "Snapdragon",
        "price": 42000,
        "office": 94,
        "gaming": 38,
        "home": 88,
        "creator": 68,
        "socket": "SNAPDRAGON-X",
        "wattage": 35,
        "capability": 76,
        "details": "Efficient ARM platform, best for office and home",
    },
    {
        "category": "Motherboard",
        "name": "B550M AM4 DDR4 Motherboard",
        "price": 8800,
        "office": 80,
        "gaming": 78,
        "home": 76,
        "creator": 76,
        "socket": "AM4",
        "ram_type": "DDR4",
        "size": "mATX",
        "tier": "budget",
        "details": "AM4, DDR4, mATX, good budget choice",
    },
    {
        "category": "Motherboard",
        "name": "A620M AM5 DDR5 Motherboard",
        "price": 9700,
        "office": 82,
        "gaming": 76,
        "home": 80,
        "creator": 76,
        "socket": "AM5",
        "ram_type": "DDR5",
        "size": "mATX",
        "tier": "budget",
        "details": "AM5, DDR5, cheaper motherboard spend",
    },
    {
        "category": "Motherboard",
        "name": "B650M AM5 DDR5 Motherboard",
        "price": 13700,
        "office": 88,
        "gaming": 88,
        "home": 84,
        "creator": 86,
        "socket": "AM5",
        "ram_type": "DDR5",
        "size": "mATX",
        "tier": "balanced",
        "details": "AM5, DDR5, balanced upgrade path",
    },
    {
        "category": "Motherboard",
        "name": "Snapdragon X Integrated Board",
        "price": 0,
        "office": 90,
        "gaming": 35,
        "home": 86,
        "creator": 64,
        "socket": "SNAPDRAGON-X",
        "ram_type": "LPDDR5X",
        "size": "Mini",
        "tier": "integrated",
        "details": "Integrated board for Snapdragon builds",
    },
    {
        "category": "RAM",
        "name": "8GB DDR4 3200MHz",
        "price": 1600,
        "office": 66,
        "gaming": 42,
        "home": 68,
        "creator": 36,
        "ram_type": "DDR4",
        "gb": 8,
        "details": "8GB DDR4, only for strict low budget",
    },
    {
        "category": "RAM",
        "name": "16GB DDR4 3200MHz",
        "price": 3100,
        "office": 84,
        "gaming": 76,
        "home": 82,
        "creator": 68,
        "ram_type": "DDR4",
        "gb": 16,
        "details": "16GB DDR4, basic gaming and daily use",
    },
    {
        "category": "RAM",
        "name": "32GB DDR4 3200MHz",
        "price": 6200,
        "office": 92,
        "gaming": 88,
        "home": 86,
        "creator": 86,
        "ram_type": "DDR4",
        "gb": 32,
        "details": "32GB DDR4, editing friendly",
    },
    {
        "category": "RAM",
        "name": "16GB DDR5 5600MHz",
        "price": 5100,
        "office": 88,
        "gaming": 82,
        "home": 84,
        "creator": 76,
        "ram_type": "DDR5",
        "gb": 16,
        "details": "16GB DDR5, modern platform",
    },
    {
        "category": "RAM",
        "name": "32GB DDR5 6000MHz",
        "price": 9800,
        "office": 96,
        "gaming": 94,
        "home": 90,
        "creator": 94,
        "ram_type": "DDR5",
        "gb": 32,
        "details": "32GB DDR5, best for high budget builds",
    },
    {
        "category": "RAM",
        "name": "32GB LPDDR5X Integrated Memory",
        "price": 0,
        "office": 94,
        "gaming": 42,
        "home": 88,
        "creator": 72,
        "ram_type": "LPDDR5X",
        "gb": 32,
        "details": "Integrated Snapdragon memory",
    },
    {
        "category": "ROM / Storage",
        "name": "256GB NVMe SSD",
        "price": 1500,
        "office": 62,
        "gaming": 35,
        "home": 58,
        "creator": 30,
        "storage_gb": 256,
        "details": "256GB NVMe, only for strict low budget",
    },
    {
        "category": "ROM / Storage",
        "name": "512GB NVMe SSD",
        "price": 2600,
        "office": 76,
        "gaming": 62,
        "home": 76,
        "creator": 54,
        "storage_gb": 512,
        "details": "512GB NVMe, light use",
    },
    {
        "category": "ROM / Storage",
        "name": "1TB NVMe SSD",
        "price": 5200,
        "office": 88,
        "gaming": 86,
        "home": 86,
        "creator": 82,
        "storage_gb": 1024,
        "details": "1TB NVMe, best default",
    },
    {
        "category": "ROM / Storage",
        "name": "2TB NVMe SSD",
        "price": 10200,
        "office": 92,
        "gaming": 94,
        "home": 90,
        "creator": 94,
        "storage_gb": 2048,
        "details": "2TB NVMe, games and large projects",
    },
    {
        "category": "Graphics Card",
        "name": "Integrated Graphics",
        "brand": "Integrated",
        "price": 0,
        "office": 70,
        "gaming": 12,
        "home": 72,
        "creator": 32,
        "wattage": 0,
        "speed": 20,
        "details": "No separate GPU",
    },
    {
        "category": "Graphics Card",
        "name": "AMD Radeon RX 7600 XT 16GB",
        "brand": "AMD",
        "price": 32500,
        "office": 78,
        "gaming": 78,
        "home": 72,
        "creator": 74,
        "wattage": 190,
        "speed": 70,
        "details": "16GB VRAM, value 1080p and entry 1440p",
    },
    {
        "category": "Graphics Card",
        "name": "AMD Radeon RX 9060 XT 8GB",
        "brand": "AMD",
        "price": 31500,
        "office": 80,
        "gaming": 82,
        "home": 74,
        "creator": 76,
        "wattage": 150,
        "speed": 76,
        "details": "Recent mainstream Radeon GPU",
    },
    {
        "category": "Graphics Card",
        "name": "AMD Radeon RX 9070 16GB",
        "brand": "AMD",
        "price": 56500,
        "office": 86,
        "gaming": 94,
        "home": 80,
        "creator": 90,
        "wattage": 220,
        "speed": 92,
        "details": "High-performance Radeon GPU",
    },
    {
        "category": "Wi-Fi Card",
        "name": "TP-Link Archer TXE75E Wi-Fi 6E",
        "price": 4200,
        "office": 82,
        "gaming": 82,
        "home": 84,
        "creator": 80,
        "wifi_rank": 76,
        "details": "PCIe card, Wi-Fi 6E with 6GHz support",
    },
    {
        "category": "Wi-Fi Card",
        "name": "TP-Link Archer TBE550E Wi-Fi 7",
        "price": 8200,
        "office": 92,
        "gaming": 94,
        "home": 92,
        "creator": 92,
        "wifi_rank": 96,
        "details": "Fast Wi-Fi 7 PCIe card",
    },
    {
        "category": "Power Supply",
        "name": "550W 80+ Bronze PSU",
        "price": 3900,
        "office": 80,
        "gaming": 72,
        "home": 78,
        "creator": 70,
        "capacity": 550,
        "quality": 68,
        "details": "550W, mainstream budget PSU",
    },
    {
        "category": "Power Supply",
        "name": "650W 80+ Gold PSU",
        "price": 6100,
        "office": 88,
        "gaming": 86,
        "home": 82,
        "creator": 84,
        "capacity": 650,
        "quality": 84,
        "details": "650W Gold, good upgrade room",
    },
    {
        "category": "Power Supply",
        "name": "750W 80+ Gold PSU",
        "price": 8100,
        "office": 90,
        "gaming": 92,
        "home": 84,
        "creator": 90,
        "capacity": 750,
        "quality": 90,
        "details": "750W Gold, strong GPU headroom",
    },
    {
        "category": "Cabinet",
        "name": "Airflow mATX Cabinet",
        "price": 2600,
        "office": 72,
        "gaming": 62,
        "home": 74,
        "creator": 62,
        "supported_sizes": ["mATX"],
        "airflow": 60,
        "details": "Compact mATX case with basic airflow",
    },
    {
        "category": "Cabinet",
        "name": "Mid Tower Airflow Cabinet",
        "price": 4300,
        "office": 82,
        "gaming": 82,
        "home": 80,
        "creator": 80,
        "supported_sizes": ["mATX", "ATX"],
        "airflow": 78,
        "details": "Good airflow and cable space",
    },
    {
        "category": "Cabinet",
        "name": "Creator Mid Tower Cabinet",
        "price": 7200,
        "office": 88,
        "gaming": 90,
        "home": 82,
        "creator": 92,
        "supported_sizes": ["mATX", "ATX"],
        "airflow": 90,
        "details": "Quiet fans, USB-C, large GPU room",
    },
]


def products_in(category):
    return [product for product in PRODUCTS if product["category"] == category]
